package crypto

import (
	"testing"
)

// Golden vector generated by jomhoor-wallet/scripts/gen-sig-vector.js using
// the wallet's exact signing scheme (deterministic sk = 0x0a1111...).
// Regenerate by running that script if the wallet algorithm ever changes.
func TestVerifyWalletSignatureFromApp(t *testing.T) {
	xHex := "0x2e62b7f82270cd122707c4ad5a9ffcef6805312e8320d3902c7289993425270d"
	yHex := "0x19808a75154c43d5e44a93dc41c556d636915fe5c1ae8d2604f72f8fd6376ba7"
	walletAddress := "0x16cd11dc0252af03b3b5607b4b614dbfc59f68183524a921b401b6d633fd5b88"
	challenge := "0xabababababababababababababababababababababababababababababababab"
	sig := "0x0711c7c10fe33099402303fade975be070d1bcb2c4788eac2d1ee3cdd9322ab0e2fca5360024955de4db41eaedc0ba8ac141c59c660f428018f6bc309484b003"

	if err := VerifyWalletAddress(xHex, yHex, walletAddress); err != nil {
		t.Errorf("VerifyWalletAddress failed: %v", err)
	} else {
		t.Log("VerifyWalletAddress: PASS")
	}

	if err := VerifyWalletSignature(xHex, yHex, challenge, sig); err != nil {
		t.Errorf("VerifyWalletSignature failed: %v", err)
	} else {
		t.Log("VerifyWalletSignature: PASS")
	}
}
